name: Flutter Workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # - uses: actions/cache@v3
      #   id: cache
      #   with:
      #     path: path/to/dependencies
      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install FLutter
        uses: subosito/flutter-action@v2.4.0
      - run: ls ..
        # if: steps.cache.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: flutter pub get && flutter pub get package/diviner/

      # - name: Format codebase
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "style(lib): apply flutter format"
      #   run: flutter format lib/ package/diviner/lib/

      - name: Analyse codebase
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      - name: Check coverage
        run: cat coverage/lcov.info

      - name: Build appbundle
        run: flutter build appbundle
