name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter pub get
        working-directory: prophecy
      - run: flutter analyse
        working-directory: prophecy
      - run: flutter test
        working-directory: prophecy
