name: Flutter Workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install FLutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get && flutter pub get package/diviner/

      - name: Format codebase
        run: flutter format lib/ package/diviner/lib/

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(lib): apply flutter format"

      - name: Analyse codebase
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      - name: Ensure coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./prophecy/coverage/lcov.info
          min_coverage: 90

      - name: Report coverage
        uses: nohmad/lcov-report-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-path: ./prophecy/coverage/lcov.info

      - name: Build appbundle
        run: flutter build appbundle

      - name: Upload appbundle
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-release.aab
          path: ./prophecy/build/app/outputs/bundle/release/app-release.aab
