name: CI

on:
  pull_request:
    branches: [master]

jobs:
  format:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter format lib/ package/diviner/lib/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style(lib): apply flutter format'
  analyze:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter pub get
      - run: flutter pub get package/diviner/
      - run: flutter analyze
  test:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter test --coverage
      - uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-android:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle
