name: Flutter Workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    defaults:
      run:
        working-directory: prophecy/
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install FLutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get && flutter pub get package/diviner/

      - name: Format codebase
        run: flutter format lib/ package/diviner/lib/

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(lib): apply flutter format"


      - name: Analyse codebase
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      - name: Check coverage
        run: cat coverage/lcov.info

      - name: Report code coverage
        uses: imciner2/run-lcov@v1
        with:
          input_directory: coverage/

      - name: Build appbundle
        run: flutter build appbundle
